# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

packages:
  bms_base: !include bms_base.yaml
  bms_temperature_sensor: !include bms_temperature_sensor_4.yaml

# +--------------------------------------+
# | Component entities                   |
# +--------------------------------------+

sensor:   
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    id: bms${bms_id}_total_voltage
    name: "${name} ${bms_name} total voltage"
    register_type: holding
    address: 0
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 2
    filters: 
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    id: bms${bms_id}_current
    name: "${name} ${bms_name} current"
    register_type: holding
    address: 1
    unit_of_measurement: "A"
    state_class: measurement
    value_type: S_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    id: bms${bms_id}_capacity_remaining_ah
    name: "${name} ${bms_name} remaining capacity"
    register_type: holding
    address: 21
    unit_of_measurement: "Ah"
    state_class: measurement
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    id: bms${bms_id}_max_charge_current
    name: "${name} ${bms_name} max charging current"
    register_type: holding
    address: 22
    unit_of_measurement: "A"
    state_class: measurement
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    id: bms${bms_id}_battery_soh
    name: "${name} ${bms_name} state of health"
    register_type: holding
    address: 23
    unit_of_measurement: "%"
    state_class: measurement
    accuracy_decimals: 0
    
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    id: bms${bms_id}_state_of_charge
    name: "${name} ${bms_name} state of charge"
    register_type: holding
    address: 24
    unit_of_measurement: "%"
    state_class: measurement
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    id: bms${bms_id}_charging_cycles_raw
    name: "${name} ${bms_name} cycle"
    register_type: holding
    address: 29
    unit_of_measurement: ""
    state_class: measurement
    accuracy_decimals: 0
    value_type: U_DWORD

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    id: bms${bms_id}_battery_capacity
    name: "${name} ${bms_name} total capacity"
    register_type: holding
    address: 37
    unit_of_measurement: "Ah"
    state_class: measurement
    accuracy_decimals: 0
    filters:
      - multiply: 0.1

## Temps
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    id: bms${bms_id}_temperature_sensor_1
    name: "${name} ${bms_name} cell temperature 1"
    register_type: holding
    address: 33
    unit_of_measurement: "°C"
    state_class: measurement
    lambda: |-
        return "%d", data[0];
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    id: bms${bms_id}_temperature_sensor_2
    name: "${name} ${bms_name} cell temperature 2"
    register_type: holding
    address: 33
    unit_of_measurement: "°C"
    state_class: measurement
    lambda: |-
        return "%d", data[1];
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    id: bms${bms_id}_temperature_sensor_3
    name: "${name} ${bms_name} cell temperature 3"
    register_type: holding
    address: 34
    unit_of_measurement: "°C"
    state_class: measurement
    lambda: |-
        return "%d", data[0];
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    id: bms${bms_id}_temperature_sensor_4
    name: "${name} ${bms_name} cell temperature 4"
    register_type: holding
    address: 34
    unit_of_measurement: "°C"
    state_class: measurement
    lambda: |-
        return "%d", data[1];
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    id: bms${bms_id}_temperature_sensor_5
    name: "${name} ${bms_name} cell temperature 5"
    register_type: holding
    address: 35
    unit_of_measurement: "°C"
    state_class: measurement
    lambda: |-
        return "%d", data[0];
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    id: bms${bms_id}_temperature_sensor_6
    name: "${name} ${bms_name} cell temperature 6"
    register_type: holding
    address: 35
    unit_of_measurement: "°C"
    state_class: measurement
    lambda: |-
        return "%d", data[1];

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} max cell temperature"
    register_type: holding
    address: 20
    unit_of_measurement: "°C"
    state_class: measurement
    value_type: S_WORD
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} average cell temperature"
    register_type: holding
    address: 19
    unit_of_measurement: "°C"
    state_class: measurement
    value_type: S_WORD
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} mosfet temperature"
    register_type: holding
    address: 18
    unit_of_measurement: "°C"
    state_class: measurement
    value_type: S_WORD
    accuracy_decimals: 0

## Cell Voltages      
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} cell voltage 01"
    register_type: holding
    address: 2
    unit_of_measurement: "V"
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} cell voltage 02"
    register_type: holding
    address: 3
    unit_of_measurement: "V"
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} cell voltage 03"
    register_type: holding
    address: 4
    unit_of_measurement: "V"
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} cell voltage 4"
    name: "${name} ${bms_name} cell voltage 04"
    register_type: holding
    address: 5
    unit_of_measurement: "V"
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} cell voltage 05"
    register_type: holding
    address: 6
    unit_of_measurement: "V"
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} cell voltage 06"
    register_type: holding
    address: 7
    unit_of_measurement: "V"
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} cell voltage 07"
    register_type: holding
    address: 8
    unit_of_measurement: "V"
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} cell voltage 08"
    register_type: holding
    address: 9
    unit_of_measurement: "V"
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} cell voltage 09"
    register_type: holding
    address: 10
    unit_of_measurement: "V"
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} cell voltage 10"
    register_type: holding
    address: 11
    unit_of_measurement: "V"
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} cell voltage 11"
    register_type: holding
    address: 12
    unit_of_measurement: "V"
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} cell voltage 12"
    register_type: holding
    address: 13
    unit_of_measurement: "V"
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} cell voltage 13"
    register_type: holding
    address: 14
    unit_of_measurement: "V"
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} cell voltage 14"
    register_type: holding
    address: 15
    unit_of_measurement: "V"
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} cell voltage 15"
    register_type: holding
    address: 16
    unit_of_measurement: "V"
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} cell voltage 16"
    register_type: holding
    address: 17
    unit_of_measurement: "V"
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

## Status
#0x0000:Inactive/Stand by
#0x0001:Inactive/Charging
#0x0002:Inactive/Discharging
#0x0004:Inactive/Protect
#0x0008:Inactive/Charging Lmt
#0x8000:Active/Stand by
#0x8001:Active/Charging
#0x8002:Active/Discharging
#0x8004:Active/Protect
#0x8008:Active/Charging Lmt

#Front Byte 0x00: Heat State-Off
#Front Byte 0x80：Heat State-On

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} status"
    register_type: holding
    address: 25
    accuracy_decimals: 0
    filters:
      - or:
        - throttle: 10s
        - delta: 1

## Error
#0x0001：Voltage error
#0x0002：Temperature error
#0x0004: Current Flow Error
#0x0010：Cell unbalance

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} error"
    register_type: holding
    address: 28
    accuracy_decimals: 0
    filters:
      - or:
        - throttle: 10s
        - delta: 1

## Warning
#0x0001：Pack OV
#0x0002：Cell OV
#0x0004：Pack UV
#0x0008：Cell UV
#0x0010：Charge OC
#0x0020：Discharge OC
#0x0040:Abnormal Ambient Temp
#0x0080: MOS Overheating
#0x0100：Charge OT
#0x0200：Discharge OT
#0x0400：Charge UT
#0x0800：Discharge UT
#0x1000：Low capacity
#0x2000: Float Stoped

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} warning"
    register_type: holding
    address: 26
    accuracy_decimals: 0
    filters:
      - or:
        - throttle: 10s
        - delta: 1

## Protection
#0x0001：Pack OV
#0x0002：Cell OV
#0x0004：Pack UV
#0x0008：Cell UV
#0x0010：Charge OC
#0x0020：Discharge OC
#0x0040: Abnormal Ambient Temp
#0x0080: MOS Overheating
#0x0100：Charge OT
#0x0200：Discharge OT
#0x0400：Charge UT
#0x0800：Discharge UT
#0x1000：Low capacity
#0x2000：Discharge SC

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} protection"
    register_type: holding
    address: 27
    accuracy_decimals: 0
    filters:
      - or:
        - throttle: 10s
        - delta: 1

## Balancer Status
#0001:Cell 1Balanced
#0002: Cell 2Balanced
#0004
# ...
#0008
#8000：Cell 16 Balanced

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} balance status"
    register_type: holding
    address: 38
    accuracy_decimals: 0

## Product
text_sensor:
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} model"
    register_type: holding
    register_count: 11
    address: 105
    response_size: 24
    raw_encode: ANSI

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} version"
    register_type: holding
    register_count: 3
    address: 117
    response_size: 6
    raw_encode: ANSI

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_bms${bms_id}
    name: "${name} ${bms_name} firmware date"
    register_type: holding
    register_count: 8
    address: 120
    response_size: 16
    raw_encode: ANSI
