# Updated : 2025.07.28
# Version : 1.3.1
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

substitutions:
  board_chip: "ESP32-S3"
  board_name: "Core S3"
  display_update_interval: "500ms"
  # Interfaces GPIOs
  # uart_esp_1 (Port A)
  tx_pin_1: '2' 
  rx_pin_1: '1'
  # uart_esp_2 (Port B)
  tx_pin_2: '9'
  rx_pin_2: '8'
  # uart_esp_3 (Port C, Commu Stack Module RS485)
  tx_pin_3: '17'
  rx_pin_3: '18'
  # canbus_commu_stack_module
  spi_mosi_pin: '37'
  spi_miso_pin: '35'
  spi_clk_pin: '36'
  mcp2515_cs_pin: '6'

packages:
  device_base: !include ../base/device_base.yaml
  device_base_wifi: !include ../base/device_base_wifi.yaml
  psram: !include board_options_PSRAM_quad_80Mhz.yaml

esp32:
  board: m5stack-atoms3
  variant: esp32s3
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

esphome:
  platformio_options:
    board_build.flash_mode: dio             # use Dual IO (dio) instead of Quad IO (qio) to prevent boot loop after flashing
    board_upload.maximum_ram_size: 524288   # total size of the internal RAM in bits, it's the same for all ESP32-S3 ( 512KB )
    build_flags:
      - -DBOARD_HAS_PSRAM
      - -mfix-esp32-psram-cache-issue

wifi:
  id: my_network
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain

logger:
  deassert_rts_dtr: true
#  baud_rate: 0 # frees the 3rd UART and avoids some bugs like "WK2168 with canbus" or "BLE client with RS485 modbus"
#  hardware_uart: USB_SERIAL_JTAG

light:
  # ESP Light used to see the inverter heartbeat
  # Internal : only specifying an id without a name will implicitly set this to true.
  - platform: binary
    id: esp_light
    output: esp_output

i2c:
  - id: cores3_i2c_bus
    sda: GPIO12
    scl: GPIO11
    scan: true

output:
  - platform: template
    id: esp_output
    type: binary
    write_action:
      - logger.log: "Inverter Heartbeat Output"
