# Updated : 2025.07.28
# Version : 1.3.1
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

substitutions:
  board_chip: "ESP32"
  board_name: "M5Stack Core2"
  display_update_interval: "50ms"
  # Interfaces GPIOs
  # uart_esp_1 (Port A)
  tx_pin_1: '32'
  rx_pin_1: '33'
  # uart_esp_2 (Port B)
  tx_pin_2: '26'
  rx_pin_2: '36'
  # uart_esp_3 (Port C, Commu Stack Module RS485)
  tx_pin_3: '14'
  rx_pin_3: '13'

  spi_bus_id: core2_spi_bu
  mcp2515_cs_pin: '27'

packages:
  device_base: !include ../base/device_base.yaml
  device_base_wifi: !include ../base/device_base_wifi.yaml
  psram: !include board_options_PSRAM_quad_80Mhz.yaml

esphome:
  name: yambmsclient
  friendly_name: YamBMSClient
  platformio_options:
    build_flags:
      - -DBOARD_HAS_PSRAM
      - -mfix-esp32-psram-cache-issue
esp32:
  board: esp32dev
  framework:
    type: esp-idf
  flash_size: 16MB
  cpu_frequency: 240MHz

external_components:
  - source:
      type: git
      url: https://github.com/RAR/esphome-axp2101
      ref: main
    refresh: 0s
    components: [ axp2101 ]

wifi:
  id: my_network
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain

logger:

light:
  # ESP Light used to see the inverter heartbeat
  # Internal : only specifying an id without a name will implicitly set this to true.
  - platform: binary
    id: esp_light
    output: esp_output

  - platform: monochromatic
    name: "LCD Backlight"
    id: display_backlight
    output: display_backlight_output
    default_transition_length: 0s
    restore_mode: RESTORE_AND_ON

binary_sensor:
  - id: !extend inverter_com_status
    on_state_change:
    - lvgl.label.update:
        id: can_status
        text_color: !lambda |-
          if (x) {
            return lv_color_hex(0x13BF13);
          }
          return lv_color_hex(0xBF1327);  

  - id: !extend esp32_online_status
    on_state_change:
    - lvgl.label.update:
        id: esp_status
        text_color: !lambda |-
          if (x) {
            return lv_color_hex(0x13BF13);
          }
          return lv_color_hex(0xBF1327); 

text_sensor:    
  - id: !extend ${yambms_id}_charging_status
    on_value:
    - lvgl.label.update:
        id: charging_status_text
        text: !lambda |-
          return x;

sensor:
  - id: !extend ${yambms_id}_battery_soc
    on_value:
    - lvgl.label.update:
        id: soc_text
        text:
          format: "%.0f%%"
          args: [ 'x' ]

  - id: !extend ${yambms_id}_total_voltage
    on_value:
    - lvgl.label.update:
        id: voltage_text
        text:
          format: "%.2fv"
          args: [ 'x' ]

  - id: !extend ${yambms_id}_current
    on_value:
    - lvgl.indicator.update:
        id: current_needle
        value: !lambda return x;
    - lvgl.label.update:
        id: current_text
        text:
          format: "%.1f a"
          args: [ 'x' ]   

  - id: !extend ${yambms_id}_power
    on_value:
    - lvgl.indicator.update:
        id: power_needle
        value: !lambda return x * 0.001;      
    - lvgl.label.update: 
        id: power_text
        text:
          format: "%.2f kw"
          args: [ 'x' ]  

  - platform: axp2101
    model: M5CORE2
    i2c_id: core2_i2c_bus
    id: core2_power
    update_interval: 30s
    battery_voltage:
      name: "Battery Voltage"
    battery_level:
      name: "Battery Level"
    battery_charging:
      name: "Battery Charging"
    
  - platform: ina3221
    i2c_id: core2_i2c_bus
    channel_1:
      shunt_resistance: 0.1 ohm
      current:
        name: "System Current"
      power:
        name: "System Power"
      bus_voltage:
        name: "System Bus Voltage"
      shunt_voltage:
        name: "System Shunt Voltage"

i2c:
  id: core2_i2c_bus
  sda: GPIO21
  scl: GPIO22
  scan: true
  
spi:
  id: ${spi_bus_id}
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO38

output:
  - platform: template
    id: esp_output
    type: binary
    write_action:
      - logger.log: "Inverter Heartbeat Output"

  - platform: template
    id: display_backlight_output
    type: float
    write_action:
      - lambda: |-
          id(core2_power).set_brightness(state);

touchscreen:
  - platform: ft63x6
    i2c_id: core2_i2c_bus
    id: my_touchscreen
            
display:
  - platform: ili9xxx
    model: M5Stack
    id: my_display
    spi_id: ${spi_bus_id}
    cs_pin: GPIO05
    dc_pin: GPIO15
    data_rate: 8000000.0
    invert_colors: true
    update_interval: ${display_update_interval}
    rotation: ${display_rotation}

font:
  - file: "gfonts://Roboto"
    id: roboto_12
    size: 12
    bpp: 4
  - file: "gfonts://Roboto"
    id: roboto_15
    size: 15    
    bpp: 4
  - file: "gfonts://Roboto"
    id: roboto_20
    size: 20
    bpp: 4
  - file: "gfonts://Roboto"
    id: roboto_45
    size: 45
    bpp: 4    

lvgl:
  displays:
    - my_display
  touchscreens:
    - my_touchscreen
  pages:
    - id: main_page
      bg_color: 0x000000
      widgets:
      - obj:
          height: 150
          width: 150
          align: BOTTOM_MID
          bg_color: 0x000000
          border_width: 0
          pad_all: 4
          y: -50
          x: -75
          widgets:
            - meter:
                height: 100%
                width: 100%
                border_width: 0
                bg_opa: TRANSP
                align: CENTER
                scales:
                  - range_from: -400
                    range_to: 400
                    angle_range: 180 # sets the total angle to 180 = starts mid left and ends mid right
                    ticks:
                      count: 0
                    indicators:
                      - line:
                          id: current_needle
                          width: 4
                          r_mod: 20 # sets line length by this much difference from the scale default radius
                          value: 0
                          color: 0xFFFFFF
                      - arc: # first half of the scale background
                          color: 0xFF3000
                          r_mod: 10 # radius difference from the scale default radius
                          width: 18
                          start_value: -400
                          end_value: 0
                      - arc: # second half of the scale background
                          color: 0x00FF00
                          r_mod: 10
                          width: 18
                          start_value: 0
                          end_value: 400
            - obj: # to cover the middle part of meter indicator line
                height: 70
                width: 70
                radius: 73
                align: CENTER
                border_width: 0
                bg_color: 0x000000
                pad_all: 0                          
            - label: # gauge numeric indicator
                id: current_text
                text_font: roboto_20
                align: CENTER
                text_color: 0xFFFFFF
                y: -2
                text: "0"
      - obj:
          height: 150
          width: 150
          align: BOTTOM_MID
          bg_color: 0x000000
          border_width: 0
          pad_all: 4
          y: -50
          x: 75
          widgets:
            - meter:
                height: 100%
                width: 100%
                border_width: 0
                bg_opa: TRANSP
                align: CENTER
                scales:
                  - range_from: -24
                    range_to: 24
                    angle_range: 180 # sets the total angle to 180 = starts mid left and ends mid right
                    ticks:
                      count: 0
                    indicators:
                      - line:
                          id: power_needle
                          width: 4
                          r_mod: 20 # sets line length by this much difference from the scale default radius
                          value: 0
                          color: 0xFFFFFF
                      - arc: # first half of the scale background
                          color: 0xFF3000
                          r_mod: 10 # radius difference from the scale default radius
                          width: 18
                          start_value: -24
                          end_value: 0
                      - arc: # second half of the scale background
                          color: 0x00FF00
                          r_mod: 10
                          width: 18
                          start_value: 0
                          end_value: 24
            - obj: # to cover the middle part of meter indicator line
                height: 70
                width: 70
                radius: 73
                align: CENTER
                border_width: 0
                bg_color: 0x000000
                pad_all: 0                          
            - label: # gauge numeric indicator
                id: power_text
                text_font: roboto_20
                align: CENTER
                text_color: 0xFFFFFF
                y: -2
                text: "0"
      - line:
          points:
            - 10, 130
            - 310, 130
          line_width: 2
          line_color: 0x747575
          line_rounded: true        
      - line:
          points:
            - 160, 130
            - 160, 200
          line_width: 2
          line_color: 0x747575
          line_rounded: true
      - line:
          points:
            - 10, 237
            - 80, 237
            - 110, 200
            - 210, 200
            - 240, 237
            - 310, 237
          line_width: 2
          line_color: 0x747575
          line_rounded: true
      - label:
          id: can_status
          align: BOTTOM_LEFT
          text_font: roboto_20
          text: "CAN"
          y: -8
          x: 20
          text_color: 0xBF1327
      - label:
          id: esp_status
          align: BOTTOM_RIGHT
          text_font: roboto_20
          text: "ESP"
          y: -8
          x: -20
          text_color: 0xBF1327                 
      - label:
          align: BOTTOM_LEFT
          id: voltage_text
          text_font: roboto_45
          text: "00.00v"
          text_color: 0xFFFFFF
          x: 13
          y: -50
      - label:
          align: BOTTOM_RIGHT
          id: soc_text
          text_font: roboto_45
          text: "00%"
          text_color: 0xFFFFFF
          x: -38
          y: -50
      - label:
          align: BOTTOM_MID
          id: charging_status_text
          text_font: roboto_20
          text: "Bulk"
          y: -8
          text_color: 0xFFFFFF
            
  style_definitions:
    - id: header_footer
      bg_color: 0x393B3B
      #bg_grad_color: 0x292828
      bg_grad_color: 0x000000
      bg_grad_dir: VER
      bg_opa: COVER
      border_opa: TRANSP
      radius: 5
      pad_all: 0
      pad_row: 0
      pad_column: 0
      border_color: 0xAEAFB0
      text_color: 0xFFFFFF
      width: 100%
      height: 20 
  top_layer:
    widgets:
      - obj:
          align: TOP_MID
          styles: header_footer
          widgets:
            - label:
                text: "YamBMS"
                align: CENTER
                text_align: CENTER
                text_color: 0xFFFFFF
                text_font: roboto_15

