# Updated : 2025.07.28
# Version : 1.3.1
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

substitutions:
  board_chip: "ESP32-S3"
  board_name: "Core S3"
  display_update_interval: "1s"
  # Interfaces GPIOs
  # uart_esp_1 (Port A)
  tx_pin_1: '2' 
  rx_pin_1: '1'
  # uart_esp_2 (Port B)
  tx_pin_2: '9'
  rx_pin_2: '8'
  # uart_esp_3 (Port C, Commu Stack Module RS485)
  tx_pin_3: '17'
  rx_pin_3: '18'

packages:
  device_base: !include ../base/device_base.yaml
  device_base_wifi: !include ../base/device_base_wifi.yaml
  psram: !include board_options_PSRAM_quad_80Mhz.yaml

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    sdkconfig_options:
        CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
        CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
        CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"
        # Moves instructions and read only data from flash into PSRAM on boot.
        # Both enabled allows instructions to execute while a flash operation is in progress without needing to be placed in IRAM.
        # Considerably speeds up mWW at the cost of using more PSRAM.
        CONFIG_SPIRAM_RODATA: "y"
        CONFIG_SPIRAM_FETCH_INSTRUCTIONS: "y"

esphome:
  on_boot:
    then:
      bm8563.read_time:

external_components:
  - source: github://m5stack/esphome-yaml/components
    components: [axp2101, aw88298, aw9523b ]

wifi:
  id: my_network
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain

logger:
  deassert_rts_dtr: true
#  baud_rate: 0 # frees the 3rd UART and avoids some bugs like "WK2168 with canbus" or "BLE client with RS485 modbus"
#  hardware_uart: USB_SERIAL_JTAG

light:
  # ESP Light used to see the inverter heartbeat
  # Internal : only specifying an id without a name will implicitly set this to true.
  - platform: binary
    id: esp_light
    output: esp_output

spi:
  - id: spi_bus
    clk_pin: GPIO36
    mosi_pin: GPIO37
    miso_pin: GPIO35

i2c:
  - id: cores3_i2c_bus
    sda: GPIO12
    scl: GPIO11
    scan: true

time:
  - platform: bm8563
    i2c_id: cores3_i2c_bus
    update_interval: never
  - platform: homeassistant
    on_time_sync:
      then:
        bm8563.write_time:    

axp2101:
  id: axp2101_pmu
  i2c_id: cores3_i2c_bus

# IO Expander
aw9523b:
  - id: aw9523b_hub
    i2c_id: cores3_i2c_bus

output:
  - platform: axp2101
    type: range
    channel: DLDO1
    id: lcd_backlight_output
    min_voltage: 2600
    max_voltage: 3300
  - platform: axp2101
    channel: ALDO1
    voltage: 1800
  - platform: axp2101
    channel: ALDO2
    voltage: 3300
  - platform: axp2101
    channel: BLDO1
    voltage: 2800
  - platform: axp2101
    channel: BLDO2
    voltage: 1500
  - platform: template
    id: esp_output
    type: binary
    write_action:
      - logger.log: "Inverter Heartbeat Output"
