# Updated : 2025.07.28
# Version : 1.3.1
# GitHub  : https://github.com/Sleeper85/esphome-yambms

# YamBMS ( Yet another multi-BMS Merging Solution )

# This YAML is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>.

substitutions:
  board_chip: "ESP32-S3"
  board_name: "Core S3"
  display_update_interval: "500ms"
  # Interfaces GPIOs
  # uart_esp_1 (Port A)
  tx_pin_1: '2' 
  rx_pin_1: '1'
  # uart_esp_2 (Port B)
  tx_pin_2: '9'
  rx_pin_2: '8'
  # uart_esp_3 (Port C, Commu Stack Module RS485)
  tx_pin_3: '17'
  rx_pin_3: '18'
  # canbus_commu_stack_module
  spi_mosi_pin: '37'
  spi_miso_pin: '35'
  spi_clk_pin: '36'
  mcp2515_cs_pin: '6'

packages:
  device_base: !include ../base/device_base.yaml
  device_base_wifi: !include ../base/device_base_wifi.yaml
  psram: !include board_options_PSRAM_quad_40Mhz.yaml

esp32:
  board: m5stack-atoms3
  variant: esp32s3
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

esphome:
  platformio_options:
    board_build.flash_mode: dio             # use Dual IO (dio) instead of Quad IO (qio) to prevent boot loop after flashing
    board_upload.maximum_ram_size: 524288   # total size of the internal RAM in bits, it's the same for all ESP32-S3 ( 512KB )
    build_flags:
      - -DBOARD_HAS_PSRAM
      - -mfix-esp32-psram-cache-issue
  libraries:
    - m5stack/M5GFX@^0.1.12
    - m5stack/M5Unified@^0.1.12
  on_boot:
    priority: 600
    then: 
      - script.execute:
          id: m5_display_set_brightness
          value: 75    

external_components:
  - source:
      type: git
      url: https://github.com/m5stack/M5CoreS3-Esphome
    components: [ board_m5cores3, m5cores3_display, m5cores3_touchscreen ]      
    refresh: 0s

wifi:
  id: my_network
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain

logger:
  baud_rate: 0 # frees the 3rd UART and avoids some bugs like "WK2168 with canbus" or "BLE client with RS485 modbus"
  hardware_uart: USB_SERIAL_JTAG

light:
  # ESP Light used to see the inverter heartbeat
  # Internal : only specifying an id without a name will implicitly set this to true.
  - platform: binary
    id: esp_light
    output: esp_output

script:
  - id: draw_display
    then:
      - component.update: my_display
  - id: m5_display_set_brightness
    parameters:
      value: int
    then:
      - lambda: M5.Display.setBrightness(value);  

spi:
  - id: cores3_spi_bus
    clk_pin: GPIO36
    mosi_pin: GPIO37

i2c:
  - id: cores3_i2c_bus
    sda: GPIO12
    scl: GPIO11
    scan: true

output:
# ESP32 board without LED
  - platform: template
    id: esp_output
    type: binary
    write_action:
      - logger.log: "Inverter Heartbeat Output"

touchscreen:
  - platform: m5cores3_touchscreen
    update_interval: 20ms
    id: my_touchscreen
    on_release:
      - if:
          condition: lvgl.is_paused
          then:
            - logger.log: "LVGL resuming"
            - lvgl.resume:
            - lvgl.widget.redraw:
            - script.execute:
                id: m5_display_set_brightness
                value: 75

display:
  # Core S3 display
  - platform: m5cores3_display
    model: ILI9342
    dc_pin: 35
    id: my_display
    update_interval: ${display_update_interval}
    rotation: ${display_rotation}

font:
  - file: "gfonts://Roboto"
    id: roboto_12
    size: 12
    bpp: 4
  - file: "gfonts://Roboto"
    id: roboto_15
    size: 15    
    bpp: 4
  - file: "gfonts://Roboto"
    id: roboto_20
    size: 20
    bpp: 4
  - file: "gfonts://Roboto"
    id: roboto_45
    size: 45
    bpp: 4    

lvgl:
  displays:
    - my_display
  touchscreens:
    - my_touchscreen
  on_idle:
    timeout: 300s
    then:
      - logger.log: "LVGL is idle"
      - script.execute:
          id: m5_display_set_brightness
          value: 0
      - lvgl.pause:
  pages:
    - id: main_page
      bg_color: 0x000000
      widgets:
      - obj:
          height: 150
          width: 150
          align: BOTTOM_MID
          bg_color: 0x000000
          border_width: 0
          pad_all: 4
          y: -50
          x: -75
          widgets:
            - meter:
                height: 100%
                width: 100%
                border_width: 0
                bg_opa: TRANSP
                align: CENTER
                scales:
                  - range_from: -400
                    range_to: 400
                    angle_range: 180 # sets the total angle to 180 = starts mid left and ends mid right
                    ticks:
                      count: 0
                    indicators:
                      - line:
                          id: current_needle
                          width: 4
                          r_mod: 20 # sets line length by this much difference from the scale default radius
                          value: 0
                          color: 0xFFFFFF
                      - arc: # first half of the scale background
                          color: 0xFF3000
                          r_mod: 10 # radius difference from the scale default radius
                          width: 18
                          start_value: -400
                          end_value: 0
                      - arc: # second half of the scale background
                          color: 0x00FF00
                          r_mod: 10
                          width: 18
                          start_value: 0
                          end_value: 400
            - obj: # to cover the middle part of meter indicator line
                height: 70
                width: 70
                radius: 73
                align: CENTER
                border_width: 0
                bg_color: 0x000000
                pad_all: 0                          
            - label: # gauge numeric indicator
                id: current_text
                text_font: roboto_20
                align: CENTER
                text_color: 0xFFFFFF
                y: -2
                text: "0"
      - obj:
          height: 150
          width: 150
          align: BOTTOM_MID
          bg_color: 0x000000
          border_width: 0
          pad_all: 4
          y: -50
          x: 75
          widgets:
            - meter:
                height: 100%
                width: 100%
                border_width: 0
                bg_opa: TRANSP
                align: CENTER
                scales:
                  - range_from: -24
                    range_to: 24
                    angle_range: 180 # sets the total angle to 180 = starts mid left and ends mid right
                    ticks:
                      count: 0
                    indicators:
                      - line:
                          id: power_needle
                          width: 4
                          r_mod: 20 # sets line length by this much difference from the scale default radius
                          value: 0
                          color: 0xFFFFFF
                      - arc: # first half of the scale background
                          color: 0xFF3000
                          r_mod: 10 # radius difference from the scale default radius
                          width: 18
                          start_value: -24
                          end_value: 0
                      - arc: # second half of the scale background
                          color: 0x00FF00
                          r_mod: 10
                          width: 18
                          start_value: 0
                          end_value: 24
            - obj: # to cover the middle part of meter indicator line
                height: 70
                width: 70
                radius: 73
                align: CENTER
                border_width: 0
                bg_color: 0x000000
                pad_all: 0                          
            - label: # gauge numeric indicator
                id: power_text
                text_font: roboto_20
                align: CENTER
                text_color: 0xFFFFFF
                y: -2
                text: "0"
      - line:
          points:
            - 10, 130
            - 310, 130
          line_width: 2
          line_color: 0x747575
          line_rounded: true        
      - line:
          points:
            - 160, 130
            - 160, 200
          line_width: 2
          line_color: 0x747575
          line_rounded: true
      - line:
          points:
            - 10, 237
            - 80, 237
            - 110, 200
            - 210, 200
            - 240, 237
            - 310, 237
          line_width: 2
          line_color: 0x747575
          line_rounded: true
       - label:
          id: can_status
          align: BOTTOM_LEFT
          text_font: roboto_20
          text: "CAN"
          y: -8
          x: 10
          text_color: 0xBF1327
       - label:
          id: esp_status
          align: BOTTOM_RIGHT
          text_font: roboto_20
          text: "ESP"
          y: -8
          x: -10
          text_color: 0xBF1327                 
      - label:
          align: BOTTOM_LEFT
          id: voltage_text
          text_font: roboto_45
          text: "00.00v"
          text_color: 0xFFFFFF
          x: 13
          y: -50
      - label:
          align: BOTTOM_RIGHT
          id: soc_text
          text_font: roboto_45
          text: "00%"
          text_color: 0xFFFFFF
          x: -38
          y: -50
      - label:
          align: BOTTOM_MID
          id: charging_status_text
          text_font: roboto_20
          text: "Bulk"
          y: -8
          text_color: 0xFFFFFF
            
  style_definitions:
    - id: header_footer
      bg_color: 0x393B3B
      #bg_grad_color: 0x292828
      bg_grad_color: 0x000000
      bg_grad_dir: VER
      bg_opa: COVER
      border_opa: TRANSP
      radius: 5
      pad_all: 0
      pad_row: 0
      pad_column: 0
      border_color: 0xAEAFB0
      text_color: 0xFFFFFF
      width: 100%
      height: 30 
  top_layer:
    widgets:
      - obj:
          align: TOP_MID
          styles: header_footer
          widgets:
            - label:
                text: "YamBMS"
                align: CENTER
                text_align: CENTER
                text_color: 0xFFFFFF
                text_font: roboto_15

